name: Transition Jira Issue to Done

on:
  pull_request:
    types: [closed]

jobs:
  transition-issue:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
      - name: Extract issue key
        id: extract-key
        run: echo "::set-output name=issue_key::$(echo ${{ github.event.pull_request.head.ref }} | grep -oE '([A-Z]+-\d+)')"
      
      - name: Transition Jira issue to Done
        if: steps.extract-key.outputs.issue_key
        run: |
          curl -X POST -u ${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_API_TOKEN }} \
          -H "Content-Type: application/json" \
          --data '{"transition": {"id": "31"}}' \
          https://<your-jira-domain>.atlassian.net/rest/api/2/issue/${{ steps.extract-key.outputs.issue_key }}/transitions
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
